# Generated by Django 5.2.4 on 2025-08-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='biografia',
            new_name='biografia_autor',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='data_nascimento',
            new_name='data_nascimento_autor',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nation',
            new_name='nation_autor',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nome',
            new_name='nome_autor',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='sobrenome',
            new_name='sobrenome_autor',
        ),
    ]
