# Generated by Django 5.2.4 on 2025-08-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_editora_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
